-- create ATTENDEES

create table ATTENDEES
(
  ID         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  EMAIL      VARCHAR(255)                            NOT NULL,
  FIRST_NAME VARCHAR(255),
  LAST_NAME  VARCHAR(255)
);

create unique index SQL180505142928030
  on ATTENDEES (EMAIL);

-- create UNSUBSCRIBE

create table UNSUBSCRIBE
(
  ID    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  EMAIL VARCHAR(255)                            NOT NULL
);

create unique index SQL180505142928180
  on UNSUBSCRIBE (EMAIL);

-- create SETTINGS

create table SETTINGS
(
  ID        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  SIGNATURE VARCHAR(2000)
);

-- create CAMPAIGN_TEMPLATES

create table CAMPAIGN_TEMPLATES
(
  ID       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  ATTENDEE BOOLEAN                                 NOT NULL,
  BODY     VARCHAR(2000)                           NOT NULL,
  EMAILS   VARCHAR(255),
  NAME     VARCHAR(255)                            NOT NULL,
  PRIORITY INTEGER,
  SUBJECT  VARCHAR(255)                            NOT NULL
);

create unique index SQL180505142928050
  on CAMPAIGN_TEMPLATES (NAME);

-- create EVENTS

create table EVENTS
(
  ID           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  DATE         VARCHAR(255) FOR BIT DATA               NOT NULL,
  DESCRIPTION  VARCHAR(2000)                           NOT NULL,
  EVENT_NUMBER INTEGER                                 NOT NULL,
  NAME         VARCHAR(255)                            NOT NULL,
  TICKETS_URL  VARCHAR(255)                            NOT NULL
);

create unique index SQL180505142928140
  on EVENTS (EVENT_NUMBER);

create unique index SQL180505142928141
  on EVENTS (NAME);

-- create TALKS

create table TALKS
(
  ID                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GOOGLE_SHEETS_TIMESTAMP VARCHAR(255)                            NOT NULL,
  THESES                  VARCHAR(5000)                           NOT NULL,
  TITLE                   VARCHAR(255)                            NOT NULL,
  EVENT_ID                BIGINT                                  NOT NULL
    constraint FK3TM258DKH2RH2S3LOG0E4FHDW
    references EVENTS
);

create unique index SQL180505142928160
  on TALKS (GOOGLE_SHEETS_TIMESTAMP);

create unique index SQL180505142928170
  on TALKS (TITLE);

-- create SPEAKERS

create table SPEAKERS
(
  ID              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  ABOUT           VARCHAR(1000)                           NOT NULL,
  COMPANY         VARCHAR(255)                            NOT NULL,
  FIRST_NAME      VARCHAR(255)                            NOT NULL,
  LAST_NAME       VARCHAR(255)                            NOT NULL,
  PHOTO_URL       VARCHAR(255)                            NOT NULL,
  POSITION        VARCHAR(255),
  WEB_PROFILE_URL VARCHAR(255),
  TALK_ID         BIGINT
    constraint FKH8EIPD243IG2GRK9O112W1RVA
    references TALKS
);

-- create CAMPAIGNS

create table CAMPAIGNS
(
  ID                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  ATTENDEE             BOOLEAN                                 NOT NULL,
  BODY                 VARCHAR(2000)                           NOT NULL,
  EMAILS               VARCHAR(255),
  NAME                 VARCHAR(255)                            NOT NULL,
  PRIORITY             INTEGER,
  PROMO_CODE           VARCHAR(255),
  STATUS               VARCHAR(255)                            NOT NULL,
  SUBJECT              VARCHAR(255)                            NOT NULL,
  CAMPAIGN_TEMPLATE_ID BIGINT
    constraint FKB2LDUGYLLE0R7F4YSSX7CPMO6
    references CAMPAIGN_TEMPLATES,
  EVENT_ID             BIGINT                                  NOT NULL
    constraint FKS182J2BBR26M45W45OIIDK6HW
    references EVENTS
);

create unique index UK_CAMPAIGNS_EVENT_NAME
  on CAMPAIGNS (EVENT_ID, NAME);

-- create EMAILS

create table EMAILS
(
  ID           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  BODY         VARCHAR(255)                            NOT NULL,
  GENERATED_AT VARCHAR(255) FOR BIT DATA               NOT NULL,
  SENT         BOOLEAN,
  SENT_AT      VARCHAR(255) FOR BIT DATA,
  SUBJECT      VARCHAR(255)                            NOT NULL,
  TO_EMAIL     VARCHAR(255)                            NOT NULL,
  CAMPAIGN_ID  BIGINT                                  NOT NULL
    constraint FK7W761XWWPJK3KHJLG8UCX8K1I
    references CAMPAIGNS
);

create unique index UK_EMAILS_CAMPAIGN_TO_EMAIL
  on EMAILS (CAMPAIGN_ID, TO_EMAIL);
