-- alter CAMPAIGNS

ALTER TABLE CAMPAIGNS ADD COLUMN NEW_BODY VARCHAR(32672) NOT NULL default '';
UPDATE CAMPAIGNS SET NEW_BODY=BODY;
ALTER TABLE CAMPAIGNS DROP COLUMN BODY;
RENAME COLUMN CAMPAIGNS.NEW_BODY TO BODY;

-- alter CAMPAIGN_TEMPLATES

ALTER TABLE CAMPAIGN_TEMPLATES ADD COLUMN NEW_BODY VARCHAR(32672) NOT NULL default '';
UPDATE CAMPAIGN_TEMPLATES SET NEW_BODY=BODY;
ALTER TABLE CAMPAIGN_TEMPLATES DROP COLUMN BODY;
RENAME COLUMN CAMPAIGN_TEMPLATES.NEW_BODY TO BODY;

-- alter EMAILS

ALTER TABLE EMAILS ADD COLUMN NEW_BODY VARCHAR(32672) NOT NULL default '';
UPDATE EMAILS SET NEW_BODY=BODY;
ALTER TABLE EMAILS DROP COLUMN BODY;
RENAME COLUMN EMAILS.NEW_BODY TO BODY;

-- alter EVENTS

ALTER TABLE EVENTS ADD COLUMN NEW_DESCRIPTION VARCHAR(32672) NOT NULL default '';
UPDATE EVENTS SET NEW_DESCRIPTION=DESCRIPTION;
ALTER TABLE EVENTS DROP COLUMN DESCRIPTION;
RENAME COLUMN EVENTS.NEW_DESCRIPTION TO DESCRIPTION;
