-- alter CAMPAIGNS

ALTER TABLE CAMPAIGNS ALTER COLUMN BODY SET DATA TYPE VARCHAR(32672);

-- alter CAMPAIGN_TEMPLATES

ALTER TABLE CAMPAIGN_TEMPLATES ALTER COLUMN BODY SET DATA TYPE VARCHAR(32672);

-- alter EMAILS

ALTER TABLE EMAILS ALTER COLUMN BODY SET DATA TYPE VARCHAR(32672);

-- alter EVENTS

ALTER TABLE EVENTS ALTER COLUMN DESCRIPTION SET DATA TYPE VARCHAR(32672);
