ALTER TABLE SPEAKERS ALTER COLUMN ABOUT SET DATA TYPE VARCHAR(32672);
ALTER TABLE SPEAKERS ALTER COLUMN PHOTO_URL SET DATA TYPE VARCHAR(500);
ALTER TABLE SPEAKERS ALTER COLUMN WEB_PROFILE_URL SET DATA TYPE VARCHAR(500);
